services:

  # Container dedicato per i dati Orekit
  orekit-data:
    build:
      context: .
      dockerfile: orekit-data.Dockerfile
    container_name: orekit-data
    volumes:
      - orekit-data-volume:/data

  db:
    image: postgres:15
    container_name: satellite-db
    environment:
      POSTGRES_DB: satellites
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: satelliteTracking
      dockerfile: Dockerfile
    container_name: satellite-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - orekit-data
    volumes:
      - orekit-data-volume:/orekit-data:ro
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/satellites
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

volumes:
  orekit-data-volume:
  postgres-data: