services:

  db:
    image: postgres:15
    container_name: satellite-db
    environment:
      POSTGRES_DB: satellites
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  app:
    build:
      context: satelliteTracking
      dockerfile: Dockerfile
    container_name: satellite-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/satellites
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin